name: Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        # 我也是fork别人的脚本，感谢前面开路的兄弟们！
        uses: askxue/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:askxue/blog-builder.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:xs1990582233/blog-builder.git